### ISSUE TITLE
edge 扩展商店找不到

### ISSUE THREAD

**Issue by Wuxiuga** [huaxiaoxuan7/CM-wangda-extension#2]
edge 扩展商店找不到 怎么使用啊

**Comment by huaxiaoxuan7** [comment]
两种方法使用，只是渔和鱼的区别：
1.本地加载使用（不受ms插件上传审核时间影响，随时可以更新）：clone仓库之后，加载解压缩的扩展（确保开启Edge扩展的开发者模式），选择[extension](https://github.com/huaxiaoxuan7/CM-wangda-extension/tree/main/extension)文件夹即可。仓库clone到本地之后，可以针对自己的需求对源代码进行修改之后，再打包加载。
2.使用[插件商店](https://microsoftedge.microsoft.com/addons/detail/djknnbiikpaagmmbklgnmbhlmgcgfkcn)直接安装在浏览器上。

**Comment by Wuxiuga** [comment]
谢谢大佬 当时不知道加载那个文件夹 已经用上了 另外大佬知道怎么获取网大上的在线考试答案吗

**Comment by Wuxiuga** [comment]
<img width="1610" alt="image" src="https://user-images.githubusercontent.com/55292351/189045980-9ebca779-e3ea-4718-ac05-122600db07ea.png">
有点问题 为什么 我挂了这么长时间还是一个都没有完成

**Comment by huaxiaoxuan7** [comment]
> <img alt="image" width="1610" src="https://user-images.githubusercontent.com/55292351/189045980-9ebca779-e3ea-4718-ac05-122600db07ea.png">
> 
> 有点问题 为什么 我挂了这么长时间还是一个都没有完成

看起来是视频并未加载，所以视频课程没有进度。
我这边测试了加载和不加载插件的情况下，Edge浏览器均无法播放，控制台网大自身的js在报红，具体原因正在看。

**Comment by huaxiaoxuan7** [comment]
> 谢谢大佬 当时不知道加载那个文件夹 已经用上了 另外大佬知道怎么获取网大上的在线考试答案吗

答案恐怕保存在服务端，目前考试页面似乎有脚步注入检测，正在研究。你有idea可以一起试试

**Comment by huaxiaoxuan7** [comment]
@Wuxiuga 
看起来是videojs的老版本在最新的chrome浏览器下播放有问题。详见[issue](https://github.com/videojs/video.js/issues/7908)
